# Generated by gallery/generate.py; do not edit.
function lootr_gallery:clear
fill 162 99 170 190 99 178 minecraft:light_gray_concrete
# chest-unopened: gold Lootr chest from persisted unopened state
setblock 164 100 172 lootr:lootr_chest[facing=south,type=single,waterlogged=false]{LootrHasBeenOpened:0b}
# chest-opened: silver Lootr chest approximation after any player opened it
setblock 168 100 172 lootr:lootr_chest[facing=east,type=single,waterlogged=false]{LootrHasBeenOpened:1b}
# trapped-unopened: gold trapped chest control
setblock 172 100 172 lootr:lootr_trapped_chest[facing=south,type=single,waterlogged=false]{LootrHasBeenOpened:0b}
# inventory-opened: silver inventory chest renderer route
setblock 176 100 172 lootr:lootr_inventory[facing=west,type=single,waterlogged=false]{LootrHasBeenOpened:1b}
# barrel-unopened: gold upright barrel
setblock 180 100 172 lootr:lootr_barrel[facing=up,open=false]{LootrHasBeenOpened:0b}
# barrel-opened-open: silver horizontal barrel using default-new texture route
setblock 184 100 172 lootr:lootr_barrel[facing=north,open=true]{LootrHasBeenOpened:1b}
# shulker-unopened: gold closed shulker facing up
setblock 188 100 172 lootr:lootr_shulker[facing=up]{LootrHasBeenOpened:0b}
# shulker-opened: silver closed shulker facing east
setblock 164 100 176 lootr:lootr_shulker[facing=east]{LootrHasBeenOpened:1b}
# sand-stage-zero: unopened suspicious sand stage zero
setblock 168 100 176 lootr:suspicious_sand[dusted=0]{LootrHasBeenOpened:0b}
# sand-stage-three: unopened suspicious sand stage three
setblock 172 100 176 lootr:suspicious_sand[dusted=3]{LootrHasBeenOpened:0b}
# gravel-opened: opened suspicious gravel override
setblock 176 100 176 lootr:suspicious_gravel[dusted=2]{LootrHasBeenOpened:1b}
# pot-unopened: intact unopened Lootr decorated pot
setblock 180 100 176 lootr:decorated_pot[cracked=false,facing=south,waterlogged=false]{LootrHasBeenOpened:0b}
# pot-opened: persisted opened Lootr pot static pose
setblock 184 100 176 lootr:decorated_pot[cracked=false,facing=east,waterlogged=false]{LootrHasBeenOpened:1b}
# trophy-stock-control: ordinary Lootr trophy remains on stock rendering
setblock 188 100 176 lootr:trophy[facing=north]
function lootr_gallery:verify
