# Generated by gallery/generate.py; do not edit.
execute unless block 164 100 172 lootr:lootr_chest[facing=south,type=single,waterlogged=false] run tellraw @a {"text":"gallery mismatch: chest-unopened","color":"red"}
execute unless block 168 100 172 lootr:lootr_chest[facing=east,type=single,waterlogged=false] run tellraw @a {"text":"gallery mismatch: chest-opened","color":"red"}
execute unless block 172 100 172 lootr:lootr_trapped_chest[facing=south,type=single,waterlogged=false] run tellraw @a {"text":"gallery mismatch: trapped-unopened","color":"red"}
execute unless block 176 100 172 lootr:lootr_inventory[facing=west,type=single,waterlogged=false] run tellraw @a {"text":"gallery mismatch: inventory-opened","color":"red"}
execute unless block 180 100 172 lootr:lootr_barrel[facing=up,open=false] run tellraw @a {"text":"gallery mismatch: barrel-unopened","color":"red"}
execute unless block 184 100 172 lootr:lootr_barrel[facing=north,open=true] run tellraw @a {"text":"gallery mismatch: barrel-opened-open","color":"red"}
execute unless block 188 100 172 lootr:lootr_shulker[facing=up] run tellraw @a {"text":"gallery mismatch: shulker-unopened","color":"red"}
execute unless block 164 100 176 lootr:lootr_shulker[facing=east] run tellraw @a {"text":"gallery mismatch: shulker-opened","color":"red"}
execute unless block 168 100 176 lootr:suspicious_sand[dusted=0] run tellraw @a {"text":"gallery mismatch: sand-stage-zero","color":"red"}
execute unless block 172 100 176 lootr:suspicious_sand[dusted=3] run tellraw @a {"text":"gallery mismatch: sand-stage-three","color":"red"}
execute unless block 176 100 176 lootr:suspicious_gravel[dusted=2] run tellraw @a {"text":"gallery mismatch: gravel-opened","color":"red"}
execute unless block 180 100 176 lootr:decorated_pot[cracked=false,facing=south,waterlogged=false] run tellraw @a {"text":"gallery mismatch: pot-unopened","color":"red"}
execute unless block 184 100 176 lootr:decorated_pot[cracked=false,facing=east,waterlogged=false] run tellraw @a {"text":"gallery mismatch: pot-opened","color":"red"}
execute unless block 188 100 176 lootr:trophy[facing=north] run tellraw @a {"text":"gallery mismatch: trophy-stock-control","color":"red"}
tellraw @a {"text":"Lootr comparison gallery checked","color":"green"}
